### ISSUE TITLE
asm hints in aco.h aren't c99?

### ISSUE THREAD

**Issue by postwait** [hnes/libaco#16]
The `asm("acosw");` in aco.h needs to be `__asm("acosw");`

**Comment by hnes** [comment]
Thank you very much for your report, @postwait.

I just committed a new update to the master branch.

PS:

if anyone interests in this topic, here are some more details about the differences between `asm` and `__asm__`:

https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Alternate-Keywords.html#Alternate-Keywords
https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html
