### ISSUE TITLE
Improve cooperation with C++ environments

### ISSUE THREAD

**Issue by elfring** [hnes/libaco#4]
[Some code from C source files](https://github.com/hnes/libaco/blob/5d4c5403b509f78ab848bcf6579b7b8a279b095b/aco.h#L18 "Update candidate") should be wrapped by the setting “[extern "C"](https://isocpp.org/wiki/faq/mixing-c-and-cpp#include-c-hdrs-personal "How can I modify my own C header files so it’s easier to #include them in C++ code?")” for C++ tools.

**Comment by hnes** [comment]
Thanks Markus for your proposal ;-)

I'll add it to the [ToDo](https://github.com/hnes/libaco#todo) list and such support will be released in v1.2.2.

**Comment by hnes** [comment]
Solved in the release of [v1.2.2](https://github.com/hnes/libaco/releases/tag/v1.2.2).
